[package]
name = "apa"
description = "A package for Arbitrary-precision arithmetics, using strings instead of u8 or i32"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
